### ISSUE TITLE
transition events don't populate transition id, label, or timestamp

### ISSUE THREAD

**Issue by Aposhian** [ros2/rcl#1019]
## Bug report

**Required Info:**

- Operating System:
  - N/A
- Installation type:
  - binaries
- Version or commit hash:
  - humble
- DDS implementation:
  -  CycloneDDS
- Client library (if applicable):
  - N/A

#### Steps to reproduce issue
Not all the fields of `lifecycle_msgs/msg/TransitionEvent` are being utilized
```
ros2 topic echo /<node>/transition_event lifecycle_msgs/msg/TransitionEvent
```

#### Expected behavior
```
timestamp: 1668097069451777251
transition:
  id: 1
  label: configure
start_state:
  id: 1
  label: unconfigured
goal_state:
  id: 10
  label: configuring
```

#### Actual behavior
```
timestamp: 0
transition:
  id: 0
  label: ''
start_state:
  id: 1
  label: unconfigured
goal_state:
  id: 10
  label: configuring
```
