### ISSUE TITLE
Support parameter descriptions in yaml parser

### ISSUE THREAD

**Issue by bpwilcox** [ros2/rcl#481]
----
## Feature request
Add support to parse parameter descriptions in yaml file.

#### Feature description

Given that parameters must now be declared and have optional ParameterDescriptors, it would be an enhancement to support parsing of a parameter description from the yaml file format. This could be convenient for users to not have to specify descriptions in code or to change their parameter settings without recompiling, but another example use case would be to control read-only or range validation for nodes with `NodeOptions.automatically_declare_from_overrides` set as true (such as a "parameter blackboard" ). Since only the default descriptors are currently declared for parameters passed via yaml, any other node can change the value to anything, which may not be desired

This feature would allow users to specify optional descriptions in the yaml file, aligning with the fields in `rcl_interfaces/ParmeterDescriptor.msg`.

An example format could be:
``` yaml
node:
  ros__parameters:
    param1: value
      read_only: true
      description: "this value is read-only"
   param2: value
      from_value: min_value
      to_value: max_value
```

#### Implementation considerations

- Requires matching changes in rclcpp to create ParameterDescriptor objects from parsed yaml and pass to Node parameter overrides
