### ISSUE TITLE
[YAML parser] Support for anchors/aliases

### ISSUE THREAD

**Issue by wieset** [ros2/rcl#563]
#### Feature description
Anchors/aliases are useful in YAML to avoid repetition, when several configuration blocks share the same group of parameters.

Example:

``` yaml
test_config: &test
  parameter_1: 123
  parameter_2: 456

device_a:
  name: "a"
  config: *test

device_b:
  name: "b"
  config: *test
```

An anchor (denoted by a leading "&")  precedes either a scalar, a sequence or a mapping. An alias (denoted by a leading "*") corresponds to an anchor of the same name. The parser should insert the anchored block at the position of the alias.

#### Implementation considerations
In libyaml, an ALIAS event is produced when reading an alias. The alias needs to be matched to a previously defined anchor of the same name. Anchors must be checked for existence and uniqueness.
